const giftProducts = [
    {
        id: 1,
        name: 'Festive Elegance Gift Basket',
        image: 'https://img.freepik.com/premium-vector/nice-looking-gift-box-front-greenery-gift-bag-vector-illustration_852896-33848.jpg',       
        rating: 4.4,
        reviews: 43,
        originalPrice: 899,
        discountedPrice: 499,
        discount: 44,
        description: 'Elevate your Diwali celebrations with the Festive Elegance Gift Basket, a curated blend of luxury...',
        type: 'gift'
    },
    {
        id: 2,
        name: 'Zen Garden Starter Kit',
        image: 'https://img.freepik.com/premium-vector/nice-looking-gift-box-front-greenery-gift-bag-vector-illustration_852896-33848.jpg', 
        rating: 4.8,
        reviews: 76,
        originalPrice: 599,
        discountedPrice: 349,
        discount: 42,
        description: 'Create your own serene space with our Zen Garden Starter Kit, complete with sand, stones, and a mini rake.',
        type: 'gift'
    },
    {
        id: 3,
        name: 'Succulent Variety Pack',
        image: 'https://img.freepik.com/premium-vector/nice-looking-gift-box-front-greenery-gift-bag-vector-illustration_852896-33848.jpg', 
        rating: 4.6,
        reviews: 32,
        originalPrice: 399,
        discountedPrice: 249,
        discount: 38,
        description: 'A delightful collection of vibrant succulents, perfect for home decor or gifting.',
        type: 'gift'
    },
    {
        id: 4,
        name: 'Indoor Herb Garden Set',
        image: 'https://img.freepik.com/premium-vector/nice-looking-gift-box-front-greenery-gift-bag-vector-illustration_852896-33848.jpg', 
        rating: 4.7,
        reviews: 55,
        originalPrice: 499,
        discountedPrice: 299,
        discount: 40,
        description: 'Grow your own culinary herbs with this all-in-one indoor herb garden set.',
        type: 'gift'
    },
    {
        id: 5,
        name: 'Air Plant Terrarium',
        image: 'https://img.freepik.com/premium-vector/nice-looking-gift-box-front-greenery-gift-bag-vector-illustration_852896-33848.jpg', 
        rating: 4.5,
        reviews: 60,
        originalPrice: 799,
        discountedPrice: 499,
        discount: 38,
        description: 'A unique air plant terrarium that adds a touch of greenery to any space.',
        type: 'gift'
    },
    {
        id: 6,
        name: 'Flowering Orchid Pot',
        image: 'https://img.freepik.com/premium-vector/nice-looking-gift-box-front-greenery-gift-bag-vector-illustration_852896-33848.jpg', 
        rating: 4.9,
        reviews: 100,
        originalPrice: 1299,
        discountedPrice: 799,
        discount: 38,
        description: 'Brighten your home with a stunning flowering orchid pot that requires minimal care.',
        type: 'gift'
    },
    {
        id: 7,
        name: 'Mini Bonsai Tree',
        image: 'https://img.freepik.com/premium-vector/nice-looking-gift-box-front-greenery-gift-bag-vector-illustration_852896-33848.jpg', 
        rating: 4.6,
        reviews: 45,
        originalPrice: 699,
        discountedPrice: 399,
        discount: 43,
        description: 'An exquisite mini bonsai tree, symbolizing harmony and peace.',
        type: 'gift'
    },
    {
        id: 8,
        name: 'Cactus Collection',
        image: 'https://img.freepik.com/premium-vector/nice-looking-gift-box-front-greenery-gift-bag-vector-illustration_852896-33848.jpg', 
        rating: 4.4,
        reviews: 27,
        originalPrice: 349,
        discountedPrice: 199,
        discount: 43,
        description: 'A charming collection of cacti, perfect for beginners and plant lovers alike.',
        type: 'gift'
    },
    {
        id: 9,
        name: 'Pet-Friendly Plant Pack',
        image: 'https://img.freepik.com/premium-vector/nice-looking-gift-box-front-greenery-gift-bag-vector-illustration_852896-33848.jpg', 
        rating: 4.5,
        reviews: 68,
        originalPrice: 599,
        discountedPrice: 359,
        discount: 40,
        description: 'Safe and non-toxic plants that are perfect for homes with pets.',
        type: 'gift'
    },
    {
        id: 10,
        name: 'Luxury Floral Arrangement',
        image: 'https://img.freepik.com/premium-vector/nice-looking-gift-box-front-greenery-gift-bag-vector-illustration_852896-33848.jpg', 
        rating: 4.8,
        reviews: 50,
        originalPrice: 899,
        discountedPrice: 549,
        discount: 39,
        description: 'A luxurious arrangement of fresh flowers that adds elegance to any occasion.',
        type: 'gift'
    },
    {
        id: 11,
        name: 'Bamboo Plant Gift Set',
        image: 'https://img.freepik.com/premium-vector/nice-looking-gift-box-front-greenery-gift-bag-vector-illustration_852896-33848.jpg', 
        rating: 4.7,
        reviews: 33,
        originalPrice: 699,
        discountedPrice: 399,
        discount: 43,
        description: 'Symbolizing luck and prosperity, this bamboo plant gift set is perfect for gifting.',
        type: 'gift'
    },
    {
        id: 12,
        name: 'Potted Peace Lily',
        image: 'https://img.freepik.com/premium-vector/nice-looking-gift-box-front-greenery-gift-bag-vector-illustration_852896-33848.jpg', 
        rating: 4.5,
        reviews: 40,
        originalPrice: 499,
        discountedPrice: 299,
        discount: 40,
        description: 'A beautiful peace lily plant that purifies the air and brings tranquility to your space.',
        type: 'gift'
    },
    {
        id: 13,
        name: 'Floral Gift Box',
        image: 'https://img.freepik.com/premium-vector/nice-looking-gift-box-front-greenery-gift-bag-vector-illustration_852896-33848.jpg', 
        rating: 4.6,
        reviews: 25,
        originalPrice: 749,
        discountedPrice: 499,
        discount: 33,
        description: 'A delightful gift box filled with assorted fresh flowers, perfect for any occasion.',
        type: 'gift'
    },
    {
        id: 14,
        name: 'Green Thumb Starter Kit',
        image: 'https://img.freepik.com/premium-vector/nice-looking-gift-box-front-greenery-gift-bag-vector-illustration_852896-33848.jpg', 
        rating: 4.8,
        reviews: 80,
        originalPrice: 799,
        discountedPrice: 449,
        discount: 44,
        description: 'Everything you need to start your gardening journey, including seeds, pots, and tools.',
        type: 'gift'
    },
    {
        id: 15,
        name: 'Vintage Plant Stand',
        image: 'https://img.freepik.com/premium-vector/nice-looking-gift-box-front-greenery-gift-bag-vector-illustration_852896-33848.jpg', 
        rating: 4.3,
        reviews: 22,
        originalPrice: 699,
        discountedPrice: 399,
        discount: 43,
        description: 'A charming vintage-style plant stand to showcase your favorite plants beautifully.',
        type: 'gift'
    },
    {
        id: 16,
        name: 'Terracotta Pot Set',
        image: 'https://img.freepik.com/premium-vector/nice-looking-gift-box-front-greenery-gift-bag-vector-illustration_852896-33848.jpg', 
        rating: 4.4,
        reviews: 30,
        originalPrice: 499,
        discountedPrice: 299,
        discount: 40,
        description: 'A set of beautifully crafted terracotta pots for all your planting needs.',
        type: 'gift'
    },
    {
        id: 17,
        name: 'Customized Plant Gift',
        image: 'https://img.freepik.com/premium-vector/nice-looking-gift-box-front-greenery-gift-bag-vector-illustration_852896-33848.jpg', 
        rating: 4.9,
        reviews: 10,
        originalPrice: 999,
        discountedPrice: 699,
        discount: 30,
        description: 'Personalize your plant gift with a custom message and selected plant type.',
        type: 'gift'
    },
    {
        id: 18,
        name: 'Charming Hanging Planter',
        image: 'https://img.freepik.com/premium-vector/nice-looking-gift-box-front-greenery-gift-bag-vector-illustration_852896-33848.jpg', 
        rating: 4.7,
        reviews: 34,
        originalPrice: 549,
        discountedPrice: 349,
        discount: 36,
        description: 'Add a touch of elegance with this charming hanging planter, perfect for indoor or outdoor use.',
        type: 'gift'
    },
    {
        id: 19,
        name: 'Herbal Tea Plant Kit',
        image: 'https://img.freepik.com/premium-vector/nice-looking-gift-box-front-greenery-gift-bag-vector-illustration_852896-33848.jpg', 
        rating: 4.6,
        reviews: 27,
        originalPrice: 499,
        discountedPrice: 299,
        discount: 40,
        description: 'Grow your own herbal tea plants and enjoy fresh brews at home.',
        type: 'gift'
    },
    {
        id: 20,
        name: 'Vintage Floral Teapot Planter',
        image: 'https://img.freepik.com/premium-vector/nice-looking-gift-box-front-greenery-gift-bag-vector-illustration_852896-33848.jpg', 
        rating: 4.8,
        reviews: 15,
        originalPrice: 599,
        discountedPrice: 399,
        discount: 33,
        description: 'A unique vintage teapot that doubles as a charming planter for your favorite flowers.',
        type: 'gift'
    },
    {
        id: 21,
        name: 'Whimsical Fairy Garden Kit',
        image: 'https://img.freepik.com/premium-vector/nice-looking-gift-box-front-greenery-gift-bag-vector-illustration_852896-33848.jpg', 
        rating: 4.5,
        reviews: 60,
        originalPrice: 699,
        discountedPrice: 449,
        discount: 36,
        description: 'Create your own magical fairy garden with this delightful kit, including tiny decorations.',
        type: 'gift'
    },
    {
        id: 22,
        name: 'Seasonal Bloom Box',
        image: 'https://img.freepik.com/premium-vector/nice-looking-gift-box-front-greenery-gift-bag-vector-illustration_852896-33848.jpg', 
        rating: 4.7,
        reviews: 33,
        originalPrice: 799,
        discountedPrice: 499,
        discount: 38,
        description: 'A seasonal selection of blooming plants delivered right to your doorstep.',
        type: 'gift'
    },
    {
        id: 23,
        name: 'Petunia Flower Basket',
        image: 'https://img.freepik.com/premium-vector/nice-looking-gift-box-front-greenery-gift-bag-vector-illustration_852896-33848.jpg', 
        rating: 4.4,
        reviews: 50,
        originalPrice: 899,
        discountedPrice: 549,
        discount: 39,
        description: 'A stunning basket of vibrant petunias, perfect for brightening any outdoor space.',
        type: 'gift'
    },
    {
        id: 24,
        name: 'Butterfly Garden Kit',
        image: 'https://img.freepik.com/premium-vector/nice-looking-gift-box-front-greenery-gift-bag-vector-illustration_852896-33848.jpg', 
        rating: 4.6,
        reviews: 22,
        originalPrice: 499,
        discountedPrice: 299,
        discount: 40,
        description: 'Encourage butterflies to visit your garden with this beautiful butterfly garden kit.',
        type: 'gift'
    }
];

const plants = [
    {
        id: 1,
        name: 'Festive Elegance Gift Basket',
        image: 'https://img.freepik.com/free-vector/flat-houseplant-collection_23-2148927488.jpg',
        rating: 4.4,
        reviews: 43,
        originalPrice: 899,
        discountedPrice: 499,
        discount: 44,
        description: 'Elevate your Diwali celebrations with the Festive Elegance Gift Basket, a curated blend of luxury...',
        type: 'plant'
    },
    {
        id: 2,
        name: 'Serene Succulent Garden',
        image: 'https://img.freepik.com/free-vector/flat-houseplant-collection_23-2148927488.jpg',
        rating: 4.5,
        reviews: 32,
        originalPrice: 599,
        discountedPrice: 349,
        discount: 42,
        description: 'Create a tranquil environment with our Serene Succulent Garden, perfect for home decor.',
        type: 'plant'
    },
    {
        id: 3,
        name: 'Majestic Monstera',
        image: 'https://img.freepik.com/free-vector/flat-houseplant-collection_23-2148927488.jpg',
        rating: 4.7,
        reviews: 58,
        originalPrice: 799,
        discountedPrice: 499,
        discount: 38,
        description: 'Bring the tropics home with a Majestic Monstera, known for its striking leaves.',
        type: 'plant'
    },
    {
        id: 4,
        name: 'Charming Cactus Collection',
        image: 'https://img.freepik.com/free-vector/flat-houseplant-collection_23-2148927488.jpg',
        rating: 4.6,
        reviews: 40,
        originalPrice: 349,
        discountedPrice: 199,
        discount: 43,
        description: 'Add a dash of character to your space with our Charming Cactus Collection.',
        type: 'plant'
    },
    {
        id: 5,
        name: 'Elegant Orchid Ensemble',
        image: 'https://img.freepik.com/free-vector/flat-houseplant-collection_23-2148927488.jpg',
        rating: 4.9,
        reviews: 100,
        originalPrice: 1299,
        discountedPrice: 799,
        discount: 38,
        description: 'A stunning array of orchids that bring elegance to any setting.',
        type: 'plant'
    },
    {
        id: 6,
        name: 'Bamboo Bliss Plant',
        image: 'https://img.freepik.com/free-vector/flat-houseplant-collection_23-2148927488.jpg',
        rating: 4.8,
        reviews: 76,
        originalPrice: 699,
        discountedPrice: 399,
        discount: 43,
        description: 'Symbolizing strength and resilience, the Bamboo Bliss Plant makes a perfect gift.',
        type: 'plant'
    },
    {
        id: 7,
        name: 'Radiant Rose Plant',
        image: 'https://img.freepik.com/free-vector/flat-houseplant-collection_23-2148927488.jpg',
        rating: 4.7,
        reviews: 55,
        originalPrice: 899,
        discountedPrice: 549,
        discount: 39,
        description: 'Brighten any space with the Radiant Rose Plant, a classic symbol of love and beauty.',
        type: 'plant'
    },
    {
        id: 8,
        name: 'Pet-Friendly Potted Plants',
        image: 'https://img.freepik.com/free-vector/flat-houseplant-collection_23-2148927488.jpg',
        rating: 4.5,
        reviews: 68,
        originalPrice: 499,
        discountedPrice: 359,
        discount: 40,
        description: 'Safe for pets, these potted plants are perfect for your furry friends.',
        type: 'plant'
    },
    {
        id: 9,
        name: 'Whimsical Fairy Fern',
        image: 'https://img.freepik.com/free-vector/flat-houseplant-collection_23-2148927488.jpg',
        rating: 4.6,
        reviews: 34,
        originalPrice: 499,
        discountedPrice: 299,
        discount: 40,
        description: 'A delightful fern that brings a touch of whimsy to any garden or home.',
        type: 'plant'
    },
    {
        id: 10,
        name: 'Lush Lavender Plant',
        image: 'https://img.freepik.com/free-vector/flat-houseplant-collection_23-2148927488.jpg',
        rating: 4.8,
        reviews: 60,
        originalPrice: 399,
        discountedPrice: 249,
        discount: 38,
        description: 'Fill your space with the soothing scent of our Lush Lavender Plant.',
        type: 'plant'
    },
    {
        id: 11,
        name: 'Tropical Foliage Bundle',
        image: 'https://img.freepik.com/free-vector/flat-houseplant-collection_23-2148927488.jpg',
        rating: 4.4,
        reviews: 27,
        originalPrice: 799,
        discountedPrice: 499,
        discount: 38,
        description: 'A vibrant mix of tropical plants to brighten your living space.',
        type: 'plant'
    },
    {
        id: 12,
        name: 'Caring Peace Lily',
        image: 'https://img.freepik.com/free-vector/flat-houseplant-collection_23-2148927488.jpg',
        rating: 4.5,
        reviews: 40,
        originalPrice: 499,
        discountedPrice: 299,
        discount: 40,
        description: 'A beautiful peace lily plant that purifies the air and brings tranquility to your space.',
        type: 'plant'
    },
    {
        id: 13,
        name: 'Happy Hoya Plant',
        image: 'https://img.freepik.com/free-vector/flat-houseplant-collection_23-2148927488.jpg',
        rating: 4.6,
        reviews: 25,
        originalPrice: 499,
        discountedPrice: 299,
        discount: 40,
        description: 'A charming Hoya plant known for its lovely flowers and trailing vines.',
        type: 'plant'
    },
    {
        id: 14,
        name: 'Delightful Dracaena',
        image: 'https://img.freepik.com/free-vector/flat-houseplant-collection_23-2148927488.jpg',
        rating: 4.5,
        reviews: 30,
        originalPrice: 399,
        discountedPrice: 249,
        discount: 38,
        description: 'The Delightful Dracaena adds a touch of elegance with its long, lush leaves.',
        type: 'plant'
    },
    {
        id: 15,
        name: 'Majestic Maple Bonsai',
        image: 'https://img.freepik.com/free-vector/flat-houseplant-collection_23-2148927488.jpg',
        rating: 4.9,
        reviews: 10,
        originalPrice: 799,
        discountedPrice: 499,
        discount: 38,
        description: 'An exquisite maple bonsai tree that symbolizes peace and tranquility.',
        type: 'plant'
    },
    {
        id: 16,
        name: 'Scented Jasmine Plant',
        image: 'https://img.freepik.com/free-vector/flat-houseplant-collection_23-2148927488.jpg',
        rating: 4.7,
        reviews: 22,
        originalPrice: 599,
        discountedPrice: 399,
        discount: 33,
        description: 'Fill your home with the sweet fragrance of our Scented Jasmine Plant.',
        type: 'plant'
    },
    {
        id: 17,
        name: 'Gorgeous Geraniums',
        image: 'https://img.freepik.com/free-vector/flat-houseplant-collection_23-2148927488.jpg',
        rating: 4.4,
        reviews: 30,
        originalPrice: 499,
        discountedPrice: 299,
        discount: 40,
        description: 'A vibrant array of geraniums to bring a splash of color to your garden.',
        type: 'plant'
    },
    {
        id: 18,
        name: 'Timeless Tulip Trio',
        image: 'https://img.freepik.com/free-vector/flat-houseplant-collection_23-2148927488.jpg',
        rating: 4.6,
        reviews: 27,
        originalPrice: 649,
        discountedPrice: 399,
        discount: 38,
        description: 'A beautiful trio of tulips that brighten any space with their colorful blooms.',
        type: 'plant'
    },
    {
        id: 19,
        name: 'Whimsical Pothos',
        image: 'https://img.freepik.com/free-vector/flat-houseplant-collection_23-2148927488.jpg',
        rating: 4.7,
        reviews: 50,
        originalPrice: 399,
        discountedPrice: 249,
        discount: 38,
        description: 'A hardy Pothos plant that thrives in various environments and adds greenery to any room.',
        type: 'plant'
    },
    {
        id: 20,
        name: 'Elegant Echeveria Set',
        image: 'https://img.freepik.com/free-vector/flat-houseplant-collection_23-2148927488.jpg',
        rating: 4.8,
        reviews: 34,
        originalPrice: 499,
        discountedPrice: 299,
        discount: 40,
        description: 'A set of stunning Echeveria plants, perfect for home decor and gifting.',
        type: 'plant'
    },
    {
        id: 21,
        name: 'Cheerful Calathea',
        image: 'https://img.freepik.com/free-vector/flat-houseplant-collection_23-2148927488.jpg',
        rating: 4.6,
        reviews: 18,
        originalPrice: 499,
        discountedPrice: 299,
        discount: 40,
        description: 'A lively Calathea plant known for its beautiful patterned leaves.',
        type: 'plant'
    },
    {
        id: 22,
        name: 'Flourishing Fiddle Leaf Fig',
        image: 'https://img.freepik.com/free-vector/flat-houseplant-collection_23-2148927488.jpg',
        rating: 4.9,
        reviews: 12,
        originalPrice: 999,
        discountedPrice: 699,
        discount: 30,
        description: 'Make a statement with the Flourishing Fiddle Leaf Fig, perfect for indoor spaces.',
        type: 'plant'
    },
    {
        id: 23,
        name: 'Charming Chia Pet',
        image: 'https://img.freepik.com/free-vector/flat-houseplant-collection_23-2148927488.jpg',
        rating: 4.5,
        reviews: 25,
        originalPrice: 299,
        discountedPrice: 199,
        discount: 33,
        description: 'A fun and quirky chia pet that grows lush green foliage in no time.',
        type: 'plant'
    },
    {
        id: 24,
        name: 'Blissful Bamboo Palm',
        image: 'https://img.freepik.com/free-vector/flat-houseplant-collection_23-2148927488.jpg',
        rating: 4.8,
        reviews: 38,
        originalPrice: 599,
        discountedPrice: 399,
        discount: 33,
        description: 'A beautiful bamboo palm that thrives indoors and purifies the air.',
        type: 'plant'
    }
];

const planters = [
    {
        id: 1,
        name: 'Elegant Ceramic Pot',
        image: 'https://img.freepik.com/free-vector/hand-drawn-houseplant-collection_23-2148911656.jpg',
        rating: 4.5,
        reviews: 34,
        originalPrice: 599,
        discountedPrice: 349,
        discount: 42,
        description: 'A beautifully designed ceramic pot that adds elegance to any plant.',
        type: 'pot'
    },
    {
        id: 2,
        name: 'Rustic Terracotta Pot',
        image: 'https://img.freepik.com/free-vector/hand-drawn-houseplant-collection_23-2148911656.jpg',
        rating: 4.6,
        reviews: 45,
        originalPrice: 299,
        discountedPrice: 199,
        discount: 33,
        description: 'Classic terracotta pot perfect for a variety of plants, with a rustic finish.',
        type: 'pot'
    },
    {
        id: 3,
        name: 'Modern Geometric Planter',
        image: 'https://img.freepik.com/free-vector/hand-drawn-houseplant-collection_23-2148911656.jpg',
        rating: 4.7,
        reviews: 28,
        originalPrice: 799,
        discountedPrice: 499,
        discount: 38,
        description: 'A stylish geometric planter that brings a contemporary touch to your decor.',
        type: 'pot'
    },
    {
        id: 4,
        name: 'Chic Hanging Pot',
        image: 'https://img.freepik.com/free-vector/hand-drawn-houseplant-collection_23-2148911656.jpg',
        rating: 4.5,
        reviews: 20,
        originalPrice: 349,
        discountedPrice: 249,
        discount: 29,
        description: 'A trendy hanging pot that saves space and adds greenery to any room.',
        type: 'pot'
    },
    {
        id: 5,
        name: 'Colorful Resin Planter',
        image: 'https://img.freepik.com/free-vector/hand-drawn-houseplant-collection_23-2148911656.jpg',
        rating: 4.8,
        reviews: 15,
        originalPrice: 499,
        discountedPrice: 299,
        discount: 40,
        description: 'A vibrant resin planter perfect for indoor and outdoor plants.',
        type: 'pot'
    },
    {
        id: 6,
        name: 'Vintage Wood Planter Box',
        image: 'https://img.freepik.com/free-vector/hand-drawn-houseplant-collection_23-2148911656.jpg',
        rating: 4.6,
        reviews: 18,
        originalPrice: 899,
        discountedPrice: 599,
        discount: 33,
        description: 'A rustic wood planter box that brings charm to your plant collection.',
        type: 'pot'
    },
    {
        id: 7,
        name: 'Elegant White Marble Pot',
        image: 'https://img.freepik.com/free-vector/hand-drawn-houseplant-collection_23-2148911656.jpg',
        rating: 4.9,
        reviews: 12,
        originalPrice: 1299,
        discountedPrice: 799,
        discount: 38,
        description: 'An elegant marble pot that exudes luxury and sophistication.',
        type: 'pot'
    },
    {
        id: 8,
        name: 'Eco-Friendly Bamboo Planter',
        image: 'https://img.freepik.com/free-vector/hand-drawn-houseplant-collection_23-2148911656.jpg',
        rating: 4.7,
        reviews: 27,
        originalPrice: 349,
        discountedPrice: 229,
        discount: 34,
        description: 'Sustainable bamboo planter perfect for eco-conscious plant lovers.',
        type: 'pot'
    },
    {
        id: 9,
        name: 'Minimalist Concrete Planter',
        image: 'https://img.freepik.com/free-vector/hand-drawn-houseplant-collection_23-2148911656.jpg',
        rating: 4.6,
        reviews: 38,
        originalPrice: 499,
        discountedPrice: 349,
        discount: 30,
        description: 'A sleek concrete planter that fits perfectly in modern interiors.',
        type: 'pot'
    },
    {
        id: 10,
        name: 'Decorative Colorful Pot',
        image: 'https://img.freepik.com/free-vector/hand-drawn-houseplant-collection_23-2148911656.jpg',
        rating: 4.8,
        reviews: 30,
        originalPrice: 399,
        discountedPrice: 249,
        discount: 38,
        description: 'Brighten up your space with this decorative and colorful planting pot.',
        type: 'pot'
    },
    {
        id: 11,
        name: 'Artisan Hand-Painted Planter',
        image: 'https://img.freepik.com/free-vector/hand-drawn-houseplant-collection_23-2148911656.jpg',
        rating: 4.5,
        reviews: 20,
        originalPrice: 699,
        discountedPrice: 399,
        discount: 43,
        description: 'A unique hand-painted planter that adds personality to your plant display.',
        type: 'pot'
    },
    {
        id: 12,
        name: 'Garden Clay Pot Set',
        image: 'https://img.freepik.com/free-vector/hand-drawn-houseplant-collection_23-2148911656.jpg',
        rating: 4.4,
        reviews: 25,
        originalPrice: 899,
        discountedPrice: 599,
        discount: 33,
        description: 'A set of garden clay pots perfect for outdoor planting.',
        type: 'pot'
    },
    {
        id: 13,
        name: 'Classic Black Pot',
        image: 'https://img.freepik.com/free-vector/hand-drawn-houseplant-collection_23-2148911656.jpg',
        rating: 4.7,
        reviews: 45,
        originalPrice: 299,
        discountedPrice: 199,
        discount: 33,
        description: 'A timeless black pot that complements any plant and decor.',
        type: 'pot'
    },
    {
        id: 14,
        name: 'Whimsical Unicorn Planter',
        image: 'https://img.freepik.com/free-vector/hand-drawn-houseplant-collection_23-2148911656.jpg',
        rating: 4.8,
        reviews: 32,
        originalPrice: 499,
        discountedPrice: 349,
        discount: 30,
        description: 'A playful unicorn planter that adds a touch of whimsy to your home.',
        type: 'pot'
    },
    {
        id: 15,
        name: 'Square Glass Planter',
        image: 'https://img.freepik.com/free-vector/hand-drawn-houseplant-collection_23-2148911656.jpg',
        rating: 4.6,
        reviews: 21,
        originalPrice: 399,
        discountedPrice: 249,
        discount: 38,
        description: 'A modern square glass planter that showcases your plants beautifully.',
        type: 'pot'
    },
    {
        id: 16,
        name: 'Elegant Gold Pot',
        image: 'https://img.freepik.com/free-vector/hand-drawn-houseplant-collection_23-2148911656.jpg',
        rating: 4.9,
        reviews: 15,
        originalPrice: 799,
        discountedPrice: 499,
        discount: 38,
        description: 'A luxurious gold pot that makes a statement in any room.',
        type: 'pot'
    },
    {
        id: 17,
        name: 'Colorful Plastic Pot Set',
        image: 'https://img.freepik.com/free-vector/hand-drawn-houseplant-collection_23-2148911656.jpg',
        rating: 4.5,
        reviews: 38,
        originalPrice: 299,
        discountedPrice: 199,
        discount: 33,
        description: 'A set of vibrant plastic pots, lightweight and perfect for indoor plants.',
        type: 'pot'
    },
    {
        id: 18,
        name: 'Natural Wood Planter',
        image: 'https://img.freepik.com/free-vector/hand-drawn-houseplant-collection_23-2148911656.jpg',
        rating: 4.6,
        reviews: 24,
        originalPrice: 699,
        discountedPrice: 499,
        discount: 29,
        description: 'A rustic natural wood planter that adds warmth to your space.',
        type: 'pot'
    },
    {
        id: 19,
        name: 'Sleek Stainless Steel Pot',
        image: 'https://img.freepik.com/free-vector/hand-drawn-houseplant-collection_23-2148911656.jpg',
        rating: 4.8,
        reviews: 30,
        originalPrice: 799,
        discountedPrice: 599,
        discount: 25,
        description: 'A contemporary stainless steel pot that brings a modern look to your plants.',
        type: 'pot'
    },
    {
        id: 20,
        name: 'Vintage Style Planter',
        image: 'https://img.freepik.com/free-vector/hand-drawn-houseplant-collection_23-2148911656.jpg',
        rating: 4.5,
        reviews: 33,
        originalPrice: 499,
        discountedPrice: 349,
        discount: 30,
        description: 'A vintage-style planter that adds a nostalgic touch to your plant collection.',
        type: 'pot'
    }
];


export {giftProducts, plants, planters}